Declare @GM_DATEID int = 17,
		@GM_MONTH varchar(2)= N'1',
		@GM_YEAR varchar(4)= N'2022',
		@GM_SETUP_SEQ int= NULL

		DROP TABLE #TEMPGMSETUP
		--DROP TABLE #TEMPCASEACT

	-- @@@  GRANTS SETUP RECORDS BY DATE ID @@@---
	SELECT GMSETUP_SEQ,GMSETUP_HIE, REPLACE(GMSETUP_HIE,'-','') GMACTPROG, GMSETUP_COUNT_TYPE, (SELECT COUNT(*) FROM GMCRIT WHERE GMCRIT_SETUP_SEQ=GMSETUP_SEQ) AS HASCRITERIA,
	(SELECT STRING_AGG(GMCRIT_RESP, ',') As ACTIVITIES  FROM GMCRIT WHERE GMCRIT_SETUP_SEQ=GMSETUP_SEQ) AS ACTIVITIES, 
	(SELECT STRING_AGG(GMCRIT_FUND_RESP, ',') As ACTIVITIES  FROM GMCRIT WHERE GMCRIT_SETUP_SEQ=GMSETUP_SEQ) AS FUNDS, 
	(SELECT STRING_AGG(GMCRIT_CQ_RESP, ',') As ACTIVITIES  FROM GMCRIT WHERE GMCRIT_SETUP_SEQ=GMSETUP_SEQ) AS  CUSTQUES,
	CAST(0 AS DECIMAL(14, 2)) AS MONTHCOUNT,0 AS HASFUND23
	INTO #TEMPGMSETUP FROM GMSETUP INNER JOIN GMSOFMST ON GMSETUP_SOFMST_ID=GMSOFMST_ID AND GMSETUP_AGENCY=GMSOFMST_AGY 
	WHERE (@GM_SETUP_SEQ IS NULL OR GMSETUP_SEQ=@GM_SETUP_SEQ) AND GMSETUP_DATE_ID=@GM_DATEID AND GMSETUP_CONTYPE='C'
	
	SELECT DISTINCT GMACTPROG FROM #TEMPGMSETUP WHERE HASCRITERIA>0 ORDER BY GMACTPROG
	
					--SELECT CASEACT_AGENCY,CASEACT_DEPT,CASEACT_PROGRAM,CASEACT_YEAR,CASEACT_APP_NO,CASEACT_SERVICE_PLAN,CASEACT_SPM_SEQ,CASEACT_BRANCH,
					--CASEACT_GROUP,CASEACT_ACTIVITY_CODE,CASEACT_SEQ,CASEACT_BULK,CASEACT_ACTY_DATE,CASEACT_SITE,CASEACT_FUND1,CASEACT_FUND2,CASEACT_FUND3,CASEACT_COST,
					--CASEACT_CASEWRKR,CASEACT_ACTY_PROG,CASEACT_DATE_LSTC,CASEACT_LSTC_OPERATOR,CASEACT_DATE_ADD,CASEACT_ADD_OPERATOR,1 AS GM_SEQ,
					--SNP_NAME_IX_LAST+' '+SNP_NAME_IX_FI AS NAME,MST_COUNTY,MST_SITE,MST_CITY,CASEACT_CUST1_CODE,CASEACT_CUST1_VALUE,CASEACT_CUST2_CODE,CASEACT_CUST2_VALUE
					--,CASEACT_CUST3_CODE,CASEACT_CUST3_VALUE,CASEACT_CUST4_CODE,CASEACT_CUST4_VALUE,CASEACT_CUST5_CODE,CASEACT_CUST5_VALUE
					--INTO #TEMPCASEACT FROM CASEACT 
					--INNER JOIN CASEMST ON MST_AGENCY=CASEACT_AGENCY AND MST_DEPT=CASEACT_DEPT AND MST_PROGRAM=CASEACT_PROGRAM AND MST_YEAR=CASEACT_YEAR
					--AND MST_APP_NO=CASEACT_APP_NO
					--INNER JOIN CASESNP ON SNP_AGENCY=CASEACT_AGENCY AND SNP_DEPT=CASEACT_DEPT AND SNP_PROGRAM=CASEACT_PROGRAM AND SNP_YEAR=CASEACT_YEAR
					--AND SNP_APP=CASEACT_APP_NO AND MST_FAMILY_SEQ=SNP_FAMILY_SEQ
					--WHERE 
					--MONTH(CASEACT_ACTY_DATE)=@GM_MONTH 
					--AND YEAR(CASEACT_ACTY_DATE)=@GM_YEAR 
					--AND CASEACT_ACTY_PROG=@PERF_AGENCY +SUBSTRING(@PERF_HIE,4,2) +SUBSTRING(@PERF_HIE,7,2)
	SELECT DISTINCT CASEACT_ACTY_PROG AS ACTPRG FROM CASEACT WHERE CASEACT_ACTY_PROG IN (SELECT GMACTPROG FROM #TEMPGMSETUP) ORDER BY CASEACT_ACTY_PROG