declare
	@GM_DATEID		INT			= 17,
	@GM_MONTH		VARCHAR(2)	= '08',
	@GM_YEAR		VARCHAR(4)	= '2022',
	@GM_SETUP_SEQ	INT			= 1729


	DROP TABLE #TEMPTABLE
	DROP TABLE #TEMPQUES

	--********************************************************************************************************************************************************---------
	--***************************************				VARIABLES & TEMP TABLES DECLARATION	BEGIN			   ***********************************************---------
	--********************************************************************************************************************************************************---------
	
	DECLARE @HEAD_ID INT, @QUERY VARCHAR(MAX)='',@GRPQUERY VARCHAR(MAX)='', @CONJ VARCHAR(1)='',@GCONJ VARCHAR(1)='',@PERF_HIE VARCHAR(8),@PERF_AGENCY VARCHAR(2),
	@Test Varchar(8000),@GROUP CHAR(1),@LOC_TYPE VARCHAR(1),@LOC_CODE VARCHAR(30),@CAPCRIT_HEAD_ID INT,@CAPCRIT_GRP_CD INT,@CAPCRIT_GRP_SEQ INT,@CAPCRIT_QUES_TYPE VARCHAR(1),
	@CAPCRIT_RESP VARCHAR(10),@CAPCRIT_CONJN VARCHAR(1)


	------////   @Act_Table DECLARATION   ////------------------
	Declare @Act_Table Table(CaseAct_AGENCY char(2),CaseAct_DEPT char(2),CaseAct_PROGRAM char(2),CaseAct_YEAR char(4),CaseAct_APP_NO char(8),CaseAct_SERVICE_PLAN int,
								 CaseAct_SPM_SEQ tinyint,CaseAct_BRANCH char(1),CaseAct_GROUP smallint,CaseAct_ACTIVITY_CODE char(10),CaseAct_SEQ smallint,
								 CaseAct_BULK char(1),CaseAct_ACTY_DATE date, CaseAct_SITE char(4),CaseAct_FUND1 varchar(10),CaseAct_FUND2 varchar(10),CaseAct_FUND3 varchar(10) ,CASEACT_COST DECIMAL(9,2),
								 CaseAct_CASEWRKR char(4),CaseAct_ACTY_PROG char(6),CaseAct_DATE_LSTC datetime,
								 CaseAct_LSTC_OPERATOR varchar(20),CaseAct_DATE_ADD datetime,CaseAct_ADD_OPERATOR varchar(20), GMSET_SEQ INT,NAME VARCHAR(50),COUNTY VARCHAR(3),MST_SITE VARCHAR(4),CITY VARCHAR(30),
								 CASEACT_CUST1_CODE varchar(6), CASEACT_CUST1_VALUE varchar(500),CASEACT_CUST2_CODE varchar(6),CASEACT_CUST2_VALUE varchar(500),CASEACT_CUST3_CODE varchar(6),CASEACT_CUST3_VALUE varchar(500),CASEACT_CUST4_CODE varchar(6),CASEACT_CUST4_VALUE varchar(500),CASEACT_CUST5_CODE varchar(6),CASEACT_CUST5_VALUE varchar(500))


	------////   @ResultTable DECLARATION   ////------------------
	DECLARE @ResultTable TABLE(AGENCY VARCHAR(2),DEPT VARCHAR(2),PROGRAM VARCHAR(2),PROGYEAR VARCHAR(4), APP_NO VARCHAR(08),NAME VARCHAR(50),ELIGIBILITY VARCHAR(1),GMCRIT_SEQ INT, AMOUNT DECIMAL(14,2), QUEST_SUM INT, QUEST_TYPE CHAR(1),  ADDOPERATOR VARCHAR(20))

	------////   @QuestionTable DECLARATION   ////------------------
	DECLARE @QuestionTable TABLE(CRITSEQ INT, APPNO VARCHAR(08),QUESGROUP VARCHAR(2),QUESCODE VARCHAR(10),QUESTYPE VARCHAR(1),QUESCONJ VARCHAR(1),QUESRESULT VARCHAR(1),QUESSTATUS VARCHAR(1),RESULTCOUNT INT,QUESTYPEDESC VARCHAR(10),CASEACT_AMOUNT DECIMAL(12,2),FUND1 VARCHAR(10),FUND2 VARCHAR(10),FUND3 VARCHAR(10), CQRESP varchar(500))

	--********************************************************************************************************************************************************---------
	--******************************************				VARIABLES & TEMP TABLES DECLARATION	END			   ******************************************---------
	--********************************************************************************************************************************************************---------

	-- @@@  GRANTS SETUP RECORDS BY DATE ID @@@---
	SELECT *,CAST(0 AS DECIMAL(14, 2)) AS MONTHCOUNT,0 AS HASFUND23, (SELECT SALQ_TYPE FROM SALQUES WHERE SALQ_ID=GMSETUP_CUSTQUES_CODE) AS GMSETUP_QTYPE
	INTO #TEMPTABLE FROM GMSETUP 
	INNER JOIN GMSOFMST ON GMSETUP_SOFMST_ID=GMSOFMST_ID AND GMSETUP_AGENCY=GMSOFMST_AGY
	WHERE (@GM_SETUP_SEQ IS NULL OR GMSETUP_SEQ=@GM_SETUP_SEQ) AND GMSETUP_DATE_ID=@GM_DATEID AND GMSETUP_CONTYPE='C'

	--SELECT * FROM #TEMPTABLE
	
	--@@@ LOOP GRANTS SETUP RECORDS STARTS @@@---
	DECLARE Cursor_Services CURSOR DYNAMIC FOR SELECT GMSETUP_SEQ,GMSETUP_HIE,GMSETUP_AGENCY,GMSETUP_LOCATION_TYPE,GMSETUP_LOCATION_CODE FROM #TEMPTABLE WHERE GMSETUP_CONTYPE='C' AND GMSETUP_DATE_ID=@GM_DATEID AND (@GM_SETUP_SEQ IS NULL OR GMSETUP_SEQ=@GM_SETUP_SEQ)
	OPEN Cursor_Services;      
     FETCH NEXT  FROM Cursor_Services INTO @HEAD_ID,@PERF_HIE,@PERF_AGENCY,@LOC_TYPE ,@LOC_CODE 
    
			 While @@FETCH_STATUS = 0
			 BEGIN
			 ---**********************************************************---
				DECLARE @SELQUES VARCHAR(1),@DELETESW VARCHAR(1)='N'

				IF EXISTS(SELECT * FROM GMCRIT WHERE GMCRIT_SETUP_SEQ=@HEAD_ID ) BEGIN 

					SELECT TOP 1  @SELQUES= GMCRIT_QUEST FROM GMCRIT WHERE GMCRIT_SETUP_SEQ=@HEAD_ID 
					
					--**********************************************----
					--- *** CASE ACT RECORDS BY EACH GMSETUP SEQ *** ---
					--**********************************************----
					SELECT CASEACT_AGENCY,CASEACT_DEPT,CASEACT_PROGRAM,CASEACT_YEAR,CASEACT_APP_NO,CASEACT_SERVICE_PLAN,CASEACT_SPM_SEQ,CASEACT_BRANCH,
					CASEACT_GROUP,CASEACT_ACTIVITY_CODE,CASEACT_SEQ,CASEACT_BULK,CASEACT_ACTY_DATE,CASEACT_SITE,CASEACT_FUND1,CASEACT_FUND2,CASEACT_FUND3,CASEACT_COST,
					CASEACT_CASEWRKR,CASEACT_ACTY_PROG,CASEACT_DATE_LSTC,CASEACT_LSTC_OPERATOR,CASEACT_DATE_ADD,CASEACT_ADD_OPERATOR,1 AS GM_SEQ,
					SNP_NAME_IX_LAST+' '+SNP_NAME_IX_FI AS NAME,MST_COUNTY,MST_SITE,MST_CITY,CASEACT_CUST1_CODE,CASEACT_CUST1_VALUE,CASEACT_CUST2_CODE,CASEACT_CUST2_VALUE
					,CASEACT_CUST3_CODE,CASEACT_CUST3_VALUE,CASEACT_CUST4_CODE,CASEACT_CUST4_VALUE,CASEACT_CUST5_CODE,CASEACT_CUST5_VALUE
					INTO #TEMPCASEACT FROM CASEACT 
					INNER JOIN CASEMST ON MST_AGENCY=CASEACT_AGENCY AND MST_DEPT=CASEACT_DEPT AND MST_PROGRAM=CASEACT_PROGRAM AND MST_YEAR=CASEACT_YEAR
					AND MST_APP_NO=CASEACT_APP_NO
					INNER JOIN CASESNP ON SNP_AGENCY=CASEACT_AGENCY AND SNP_DEPT=CASEACT_DEPT AND SNP_PROGRAM=CASEACT_PROGRAM AND SNP_YEAR=CASEACT_YEAR
					AND SNP_APP=CASEACT_APP_NO AND MST_FAMILY_SEQ=SNP_FAMILY_SEQ
					WHERE 
					MONTH(CASEACT_ACTY_DATE)=@GM_MONTH 
					AND YEAR(CASEACT_ACTY_DATE)=@GM_YEAR 
					AND CASEACT_ACTY_PROG=@PERF_AGENCY +SUBSTRING(@PERF_HIE,4,2) +SUBSTRING(@PERF_HIE,7,2)

					
					-- COMENTED BY KRANTHI AS OF NOW COMENTING  LOCATION BASED FUNCTION TO MATCH THE COUNTS ON 07/27/2021
					--IF(@LOC_TYPE='1') DELETE #TEMPCASEACT WHERE MST_COUNTY != @LOC_CODE
					--ELSE IF(@LOC_TYPE='2') DELETE #TEMPCASEACT WHERE MST_SITE != @LOC_CODE
					--ELSE IF(@LOC_TYPE='3') DELETE #TEMPCASEACT WHERE MST_CITY != @LOC_CODE

					--///// COPPYING TEMPCASEACT TABLE TO ACT_TABLE	/////--
					IF(@SELQUES!='O') INSERT INTO @Act_Table SELECT * FROM #TEMPCASEACT
					--select * from @Act_Table
					--SELECT COUNT(*),CASEACT_ACTY_PROG,@HEAD_ID,@PERF_HIE FROM @Act_Table GROUP BY CASEACT_ACTY_PROG

					--///// COPPYING DISTINCT APPNO RECORDS INTO @ResultTable TABLE FROM @Act_Table /////---
					INSERT INTO @ResultTable SELECT DISTINCT CaseAct_AGENCY,CaseAct_DEPT,CaseAct_PROGRAM,CaseAct_YEAR, CaseAct_APP_NO,NAME,'N',@HEAD_ID,0,0,NULL,CaseAct_ADD_OPERATOR FROM @Act_Table
					--select * from @ResultTable
					--SELECT * FROM @ResultTable
					SET @DELETESW='Y'
					--***************************************************----
					--- *** LOOP DISTINCT APPNO IN @Act_Table BEGINS  *** ---
					--***************************************************----

								-- ***** VARIABLES DECLARATION BEGINS***---
									DECLARE @CASEACT_AGENCY VARCHAR(2),@CASEACT_DEPT VARCHAR(2),@CASEACT_PROGRAM VARCHAR(2),@CASEACT_YEAR VARCHAR(4),@CASEACT_APP_NO VARCHAR(8),
									@GMCRIT_FUND_RESP VARCHAR(MAX),@GMCRIT_COUNT_TYPE CHAR(2),@GMCRIT_COUNT_RESP VARCHAR(20),@hasFunds23 int=0,@GMCRIT_CQ_RESP VARCHAR(500)
								-- ***** VARIABLES DECLARATION END***---
								 
								DECLARE Cursor_Apps CURSOR DYNAMIC FOR SELECT DISTINCT CASEACT_AGENCY,CASEACT_DEPT,CASEACT_PROGRAM,CASEACT_YEAR,CASEACT_APP_NO FROM @Act_Table  
								OPEN Cursor_Apps;      
								FETCH NEXT  FROM Cursor_Apps INTO @CASEACT_AGENCY,@CASEACT_DEPT,@CASEACT_PROGRAM,@CASEACT_YEAR,@CASEACT_APP_NO
								While @@FETCH_STATUS = 0
								BEGIN

								DECLARE @CQSUMAMOUNTS DECIMAL(14,2)= 0;
										/***** LOOP CRITERIA RECORDS BY APP NO BEGINS  */
											DECLARE @TEMPCOUNT INT,@SUMAMOUNT DECIMAL(12,2)=0,@FUND1 VARCHAR(10),@FUND2 VARCHAR(10),@FUND3 VARCHAR(10),@ISCountable CHAR(1)='N',@CQ_RESP VARCHAR(500)
											DECLARE Cursor_CRITERIA CURSOR DYNAMIC FOR SELECT GMCRIT_SETUP_SEQ,GMCRIT_GRP_CODE,GMCRIT_GRP_SEQ,GMCRIT_QUEST,GMCRIT_RESP,GMCRIT_CONJN,GMCRIT_COUNT_TYPE,GMCRIT_COUNT_RESP,GMCRIT_FUND_RESP, GMCRIT_CQ_RESP FROM GMCRIT WHERE GMCRIT_SETUP_SEQ=@HEAD_ID AND GMCRIT_GRP_SEQ!=0 ORDER BY GMCRIT_SETUP_SEQ,GMCRIT_GRP_CODE,GMCRIT_GRP_SEQ
											OPEN Cursor_CRITERIA;
											FETCH NEXT FROM Cursor_CRITERIA INTO @CAPCRIT_HEAD_ID,@CAPCRIT_GRP_CD,@CAPCRIT_GRP_SEQ,@CAPCRIT_QUES_TYPE,@CAPCRIT_RESP,@CAPCRIT_CONJN,@GMCRIT_COUNT_TYPE,@GMCRIT_COUNT_RESP,@GMCRIT_FUND_RESP,@GMCRIT_CQ_RESP
											While @@FETCH_STATUS = 0
											BEGIN

												IF(@CAPCRIT_QUES_TYPE='A') BEGIN

												--* MODIFIED by KRANTHI on 06/11/2021:: To make Amount count zero when the Activity has Fund2 and Fund 3*--
													
												IF((SELECT COUNT(*) FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP 
														AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) )) AND ((CaseAct_FUND2 IS NOT NULL)OR(CaseAct_FUND3 IS NOT NULL)))>0) BEGIN
															SET @hasFunds23 = @hasFunds23+1
														END

													IF(@GMCRIT_FUND_RESP IS NOT NULL) BEGIN
														SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO),@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table 
														WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP 
														AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
														
														
														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3  FROM @Act_Table 
														WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP 
														AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
													END

													ELSE BEGIN 

														SET @hasFunds23 = 0;
														SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO),@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table 
														WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP)
														
														
														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3  FROM @Act_Table 
														WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP)
													END

													END
												IF(@CAPCRIT_QUES_TYPE='S') BEGIN
												--SELECT * FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP) -- AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
													IF(@GMCRIT_FUND_RESP IS NOT NULL) BEGIN
														SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO),@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP  AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3  FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP  AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
													END
													ELSE BEGIN 
														SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO),@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP)
														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3  FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP) 
													END
												END
												IF(@CAPCRIT_QUES_TYPE='Q') 
													--SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO) FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP) -- AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
													
													IF(@GMCRIT_FUND_RESP IS NOT NULL AND @GMCRIT_CQ_RESP IS NOT NULL) BEGIN
														SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO),@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO 
														AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP  
														AND (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) 
														OR CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) 
														OR CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))) 
														AND ( (CASEACT_CUST1_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST1_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) 
														OR (CASEACT_CUST2_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST2_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) 
														OR (CASEACT_CUST3_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST3_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) 
														OR (CASEACT_CUST4_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST4_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) 
														OR (CASEACT_CUST5_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST5_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,',')))))

														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3, 
														@CQ_RESP= CASE WHEN CASEACT_CUST1_VALUE IS NOT NULL THEN CASEACT_CUST1_VALUE
																	   WHEN CASEACT_CUST2_VALUE IS NOT NULL THEN CASEACT_CUST2_VALUE
																	   WHEN CASEACT_CUST3_VALUE IS NOT NULL THEN CASEACT_CUST3_VALUE
																	  WHEN CASEACT_CUST4_VALUE IS NOT NULL THEN CASEACT_CUST4_VALUE
																	  WHEN CASEACT_CUST5_VALUE IS NOT NULL THEN CASEACT_CUST5_VALUE ELSE NULL END FROM @Act_Table 
																	  WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND 
																	  (
																	  
																	  CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP  AND 
																	  (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR 
																	  CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR 
																	  CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
													END

													ELSE IF(@GMCRIT_FUND_RESP IS NULL AND @GMCRIT_CQ_RESP IS NOT NULL) BEGIN
														SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO),@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP AND ( (CASEACT_CUST1_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) AND  CASEACT_CUST1_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) OR (CASEACT_CUST2_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) AND  CASEACT_CUST2_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) OR (CASEACT_CUST3_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) AND  CASEACT_CUST3_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) OR (CASEACT_CUST4_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) AND  CASEACT_CUST4_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,','))) OR (CASEACT_CUST5_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) AND  CASEACT_CUST5_VALUE IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_CQ_RESP,',')))))
														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3, 
														@CQ_RESP= CASE WHEN CASEACT_CUST1_VALUE IS NOT NULL THEN CASEACT_CUST1_VALUE
																	   WHEN CASEACT_CUST2_VALUE IS NOT NULL THEN CASEACT_CUST2_VALUE
																	   WHEN CASEACT_CUST3_VALUE IS NOT NULL THEN CASEACT_CUST3_VALUE
																	   WHEN CASEACT_CUST4_VALUE IS NOT NULL THEN CASEACT_CUST4_VALUE
																	  WHEN CASEACT_CUST5_VALUE IS NOT NULL THEN CASEACT_CUST5_VALUE ELSE NULL END
														
														  FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO 
														  AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP  AND 
														  (CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR 
														  CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR 
														  CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
													END

													ELSE IF(@GMCRIT_FUND_RESP IS NOT NULL AND @GMCRIT_CQ_RESP IS NULL) BEGIN

														DECLARE @QUESTYPE VARCHAR(2)
														SELECT @QUESTYPE = (SELECT SALQ_TYPE FROM SALQUES WHERE SALQ_ID = (SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID))

														
														SELECT @TEMPCOUNT= CASE WHEN @QUESTYPE='T' THEN COUNT(CASEACT_APP_NO) WHEN @QUESTYPE='N' THEN 
														--SUM(ISNULL(CAST(CASEACT_CUST1_VALUE AS INT),0.00)) 
														
														(CASE WHEN SUM(CAST(CASEACT_CUST1_VALUE AS INT)) IS NOT NULL THEN SUM(CAST(CASEACT_CUST1_VALUE AS INT)) ELSE 
															CASE WHEN SUM(CAST(CASEACT_CUST2_VALUE AS INT)) IS NOT NULL THEN  SUM(ISNULL(CAST(CASEACT_CUST2_VALUE AS INT),0.00))ELSE  
															CASE WHEN SUM(CAST(CASEACT_CUST3_VALUE AS INT)) IS NOT NULL THEN  SUM(ISNULL(CAST(CASEACT_CUST3_VALUE AS INT),0.00)) ELSE 
															CASE WHEN SUM(CAST(CASEACT_CUST4_VALUE AS INT)) IS NOT NULL THEN  SUM(ISNULL(CAST(CASEACT_CUST4_VALUE AS INT),0.00)) ELSE 
															CASE WHEN SUM(CAST(CASEACT_CUST5_VALUE AS INT)) IS NOT NULL THEN  SUM(ISNULL(CAST(CASEACT_CUST5_VALUE AS INT),0.00)) ELSE 0 
															END END END END END
														) 
														
														END,
														@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table 
														WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND 
														(CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP  
														AND 
														(CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) 
														OR CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) 
														OR CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')))
														
														AND ( (CASEACT_CUST1_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST1_VALUE IS NOT NULL) 
														OR (CASEACT_CUST2_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST2_VALUE  IS NOT NULL) 
														OR (CASEACT_CUST3_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST3_VALUE  IS NOT NULL) 
														OR (CASEACT_CUST4_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST4_VALUE IS NOT NULL) 
														OR (CASEACT_CUST5_CODE =(SELECT ISNULL(GMSETUP_CUSTQUES_CODE,NULL) FROM GMSETUP WHERE GMSETUP_SEQ=@CAPCRIT_HEAD_ID) 
														AND  CASEACT_CUST5_VALUE  IS NOT NULL))
														)

														SET @CQSUMAMOUNTS = @CQSUMAMOUNTS+ @TEMPCOUNT;
														
														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3, 
														@CQ_RESP= CASE WHEN CASEACT_CUST1_VALUE IS NOT NULL THEN CASEACT_CUST1_VALUE
																		WHEN CASEACT_CUST2_VALUE IS NOT NULL THEN CASEACT_CUST2_VALUE
																		WHEN CASEACT_CUST3_VALUE IS NOT NULL THEN CASEACT_CUST3_VALUE
																		WHEN CASEACT_CUST4_VALUE IS NOT NULL THEN CASEACT_CUST4_VALUE
																		WHEN CASEACT_CUST5_VALUE IS NOT NULL THEN CASEACT_CUST5_VALUE ELSE NULL END
																		FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND 
																		(CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP  AND 
																		(CaseAct_FUND1 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR 
																		CaseAct_FUND2 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,',')) OR 
																		CaseAct_FUND3 IN (SELECT ColumnValue FROM dbo.Split_String_To_Table(@GMCRIT_FUND_RESP,','))))
													END
													ELSE BEGIN 
														SELECT @TEMPCOUNT= COUNT(CASEACT_APP_NO),@SUMAMOUNT= SUM(ISNULL(CASEACT_COST,0.00)) FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP)
														SELECT TOP 1 @FUND1=CaseAct_FUND1, @FUND2=CaseAct_FUND2,@FUND3=CaseAct_FUND3  FROM @Act_Table WHERE CaseAct_APP_NO=@CASEACT_APP_NO AND (CaseAct_ACTIVITY_CODE=@CAPCRIT_RESP) 
													END

												IF(@TEMPCOUNT>0) begin
													INSERT INTO @QuestionTable SELECT @CAPCRIT_HEAD_ID, @CASEACT_APP_NO,@CAPCRIT_GRP_CD,@CAPCRIT_RESP,@CAPCRIT_QUES_TYPE,@CAPCRIT_CONJN,'Y',NULL,@TEMPCOUNT,CASE WHEN (@CAPCRIT_QUES_TYPE='A' OR @CAPCRIT_QUES_TYPE='S' OR @CAPCRIT_QUES_TYPE='Q') THEN 'Act'  WHEN @CAPCRIT_QUES_TYPE='F' THEN 'Fund' WHEN @CAPCRIT_QUES_TYPE='O' THEN 'Outcome' WHEN @CAPCRIT_QUES_TYPE='Q' THEN 'Custom Question' END,@SUMAMOUNT,@FUND1,@FUND2,@FUND3,@CQ_RESP
													SET @ISCountable='Y'
												END
												ELSE
													INSERT INTO @QuestionTable SELECT @CAPCRIT_HEAD_ID, @CASEACT_APP_NO,@CAPCRIT_GRP_CD,@CAPCRIT_RESP,@CAPCRIT_QUES_TYPE,@CAPCRIT_CONJN,'N',NULL,@TEMPCOUNT,CASE WHEN (@CAPCRIT_QUES_TYPE='A' OR @CAPCRIT_QUES_TYPE='S' OR @CAPCRIT_QUES_TYPE='Q') THEN 'Act'  WHEN @CAPCRIT_QUES_TYPE='F' THEN 'Fund' WHEN @CAPCRIT_QUES_TYPE='O' THEN 'Outcome'  WHEN @CAPCRIT_QUES_TYPE='Q' THEN 'Custom Question' END,@SUMAMOUNT,@FUND1,@FUND2,@FUND3,@CQ_RESP


											FETCH NEXT FROM Cursor_CRITERIA INTO @CAPCRIT_HEAD_ID,@CAPCRIT_GRP_CD,@CAPCRIT_GRP_SEQ,@CAPCRIT_QUES_TYPE,@CAPCRIT_RESP,@CAPCRIT_CONJN,@GMCRIT_COUNT_TYPE,@GMCRIT_COUNT_RESP,@GMCRIT_FUND_RESP,@CQ_RESP
											END    
											close Cursor_CRITERIA;
											Deallocate Cursor_CRITERIA;

										/***** LOOP CRITERIA RECORDS BY APP NO END  */
										
										
										IF(@ISCountable='Y')	BEGIN
											UPDATE @ResultTable SET ELIGIBILITY='Y',AMOUNT=ISNULL((SELECT SUM(CASEACT_AMOUNT) FROM @QuestionTable WHERE APPNO=@CASEACT_APP_NO 
											AND CRITSEQ=@HEAD_ID),0),QUEST_TYPE=(SELECT GMSETUP_QTYPE FROM #TEMPTABLE WHERE GMSETUP_SEQ=@HEAD_ID),QUEST_SUM=@CQSUMAMOUNTS WHERE APP_NO=@CASEACT_APP_NO AND AGENCY=@CASEACT_AGENCY AND DEPT=@CASEACT_DEPT AND PROGRAM=@CASEACT_PROGRAM 
											AND PROGYEAR=@CASEACT_YEAR AND GMCRIT_SEQ=@HEAD_ID
										END

								FETCH NEXT  FROM Cursor_Apps INTO @CASEACT_AGENCY,@CASEACT_DEPT,@CASEACT_PROGRAM,@CASEACT_YEAR,@CASEACT_APP_NO
								END
								close Cursor_Apps;
								Deallocate Cursor_Apps;		

					--***********************************************----
					--- *** LOOP DISTINCT APPNO IN @Act_Table END *** ---
					--***********************************************----
			
				END

				--select * from @QuestionTable where RESULTCOUNT=1
				--select * from @ResultTable

			 ---***********************************************************---
			-- UPDATE @ResultTable SET ELIGIBILITY='Y',AMOUNT=ISNULL((SELECT SUM(CASEACT_AMOUNT) FROM @QuestionTable WHERE APPNO=@CASEACT_APP_NO AND CRITSEQ=@HEAD_ID),0) WHERE APP_NO=@CASEACT_APP_NO AND AGENCY=@CASEACT_AGENCY AND DEPT=@CASEACT_DEPT AND PROGRAM=@CASEACT_PROGRAM AND PROGYEAR=@CASEACT_YEAR AND GMCRIT_SEQ=@HEAD_ID
			
			 UPDATE #TEMPTABLE SET 
			 MONTHCOUNT=CAST((SELECT COUNT(DISTINCT(APP_NO)) FROM @ResultTable WHERE ELIGIBILITY='Y' AND GMCRIT_SEQ=@HEAD_ID) AS decimal(14,2)) 
			 WHERE GMSETUP_SEQ=@HEAD_ID AND GMSETUP_COUNT_TYPE='CS'
			--select * from #TEMPTABLE

			UPDATE #TEMPTABLE SET 
			MONTHCOUNT= ISNULL((SELECT SUM(AMOUNT) FROM @ResultTable WHERE ELIGIBILITY='Y' AND GMCRIT_SEQ=@HEAD_ID),0), 
			HASFUND23 = ISNULL(@hasFunds23,0)
			WHERE GMSETUP_SEQ=@HEAD_ID AND GMSETUP_COUNT_TYPE='CA'
			--select * from #TEMPTABLE

			
			 UPDATE #TEMPTABLE SET 
			 MONTHCOUNT= ((SELECT COUNT(DISTINCT(APP_NO)) FROM @ResultTable WHERE ELIGIBILITY='Y' AND GMCRIT_SEQ=@HEAD_ID )) 
			 WHERE GMSETUP_SEQ=@HEAD_ID AND GMSETUP_COUNT_TYPE='CQ' AND GMSETUP_QTYPE!='N'

			 
			 UPDATE #TEMPTABLE SET 
			 MONTHCOUNT= ((SELECT SUM(QUEST_SUM) FROM @ResultTable WHERE ELIGIBILITY='Y' AND GMCRIT_SEQ=@HEAD_ID )) 
			 WHERE GMSETUP_SEQ=@HEAD_ID AND GMSETUP_COUNT_TYPE='CQ' AND GMSETUP_QTYPE='N'

			-- select * from #TEMPTABLE

			SET @hasFunds23=0;
			 
			 IF(@DELETESW='Y') BEGIN
							if exists(select count(CASEACT_APP_NO) from #TEMPCASEACT)
								DROP TABLE #TEMPCASEACT
							--if exists(select count(CASEMS_APP_NO) from #TEMPCASEMS)
							--	DROP TABLE #TEMPCASEMS
							if exists(select count(*) from @Act_Table)
								delete @Act_Table
			END

			 FETCH NEXT  FROM Cursor_Services INTO @HEAD_ID,@PERF_HIE,@PERF_AGENCY,@LOC_TYPE ,@LOC_CODE 
			END
	close Cursor_Services;
	Deallocate Cursor_Services;

	--@@@ LOOP GRANTS SETUP RECORDS ENDS @@@---

	

	SELECT 
	(CASE WHEN (HASFUND23>0 AND GMSETUP_COUNT_TYPE='CA') THEN 0.00 ELSE MONTHCOUNT END) MONTHCOUNT
	, MONTHCOUNT AS OMONTHCOUNT,HASFUND23, GMSETUP_COUNT_TYPE, * FROM #TEMPTABLE order by GMSETUP_SEQ

	DECLARE   @SQLQuery AS NVARCHAR(MAX)
	DECLARE   @PivotColumns AS NVARCHAR(MAX)=NULL
	--DECLARE	  @PivotCQcolumns as nvarchar(MAX)=NULL

	SELECT   @PivotColumns= COALESCE(@PivotColumns + ',','') + QUOTENAME( QUESTYPEDESC+' '+ QUESCODE) 
	FROM (SELECT DISTINCT QUESTYPEDESC,QUESCODE FROM @QuestionTable ) AS PivotExample  ORDER BY QUESTYPEDESC,QUESCODE

	--SELECT DISTINCT QUESTYPEDESC,QUESCODE FROM @QuestionTable 
	--SELECT @PivotColumns AS QUESTION

	--SELECT * FROM @QuestionTable

	SELECT DISTINCT (SELECT GMMAST_DESC FROM GMMAST WHERE GMMAST_CODE=GMSOFMST_BUDCAT  AND GMMAST_TYPE='BUDC') BUDGET,
			(GMSOFMST_SOFID + CASE WHEN  GMSOFMST_YEAR='  ' THEN '' ELSE ' - '+ GMSOFMST_YEAR END) SOFID,GMSETUP_PERF_DESC as Performance_Measure, QUESTYPE as QType,
			(SELECT GMMAST_DESC FROM GMMAST 
			WHERE GMMAST_CODE=GMSOFMST_PRGCOD  AND GMMAST_TYPE='PRGM')PROGRAM, 
			AGENCY+DEPT+PROGRAM+CASE WHEN PROGYEAR='' THEN '    ' ELSE PROGYEAR END+APP_NO AS APP_NO,NAME,GMSETUP_HIE AS ACTIVITY_PROGRAM, 
			ELIGIBILITY, QUESRESULT , QUESTYPEDESC +' '+ QUESCODE AS QUESTION,CRITSEQ,FUND1,FUND2,FUND3,
			(SELECT SALQR_DESC FROM SALQRESP WHERE SALQR_Q_ID=GMSETUP_CUSTQUES_CODE AND SALQR_CODE=CQRESP)CQRESP,GMSETUP_CUSTQUES_CODE as CQCode,
			(select SALQ_DESC from SALQUES where SALQ_ID=GMSETUP_CUSTQUES_CODE) CQDESC
			INTO #TEMPQUES FROM @ResultTable INNER JOIN @QuestionTable ON APP_NO=APPNO AND CRITSEQ=GMCRIT_SEQ AND RESULTCOUNT>0
			LEFT JOIN GMSETUP ON GMSETUP_SEQ=GMCRIT_SEQ 
			LEFT JOIN GMSOFMST ON GMSOFMST_ID=GMSETUP_SOFMST_ID AND GMSETUP_AGENCY=GMSOFMST_AGY
	
	
	--select * from #TEMPQUES
	--SELECT   @PivotCQcolumns= COALESCE(@PivotCQcolumns + ',','') + QUOTENAME( 'CQ'+' '+ CQCode) 
	--FROM (SELECT DISTINCT CQCode FROM #TEMPQUES ) AS PivotExample  ORDER BY CQCode
	--SELECT @PivotCQcolumns AS CQcode

	--SELECT * 
	--FROM #TEMPQUES T INNER JOIN @ResultTable R ON R.AGENCY+R.DEPT+R.PROGRAM+CASE WHEN R.PROGYEAR='' THEN '    ' ELSE R.PROGYEAR END+R.APP_NO=T.APP_NO AND R.GMCRIT_SEQ=T.CRITSEQ

	ALTER TABLE #TEMPQUES ADD ADDOPERATOR VARCHAR(20)

	UPDATE #TEMPQUES SET ADDOPERATOR=(SELECT TOP 1 ADDOPERATOR FROM @ResultTable WHERE  GMCRIT_SEQ=CRITSEQ)
	--FROM #TEMPQUES T INNER JOIN @ResultTable R ON R.AGENCY+R.DEPT+R.PROGRAM+R.PROGYEAR+R.APP_NO=T.APP_NO AND R.GMCRIT_SEQ=T.CRITSEQ

	INSERT INTO #TEMPQUES (BUDGET,PROGRAM,SOFID,Performance_measure) SELECT (SELECT GMMAST_DESC FROM GMMAST WHERE GMMAST_CODE=GMSOFMST_BUDCAT  AND GMMAST_TYPE='BUDC') BUDGET,
	(SELECT GMMAST_DESC FROM GMMAST WHERE GMMAST_CODE=GMSOFMST_PRGCOD  AND GMMAST_TYPE='PRGM')PROGRAM, 
	(GMSOFMST_SOFID + CASE WHEN  GMSOFMST_YEAR='  ' THEN '' ELSE ' - '+ GMSOFMST_YEAR END) SOFID,GMSETUP_PERF_DESC as Performance_Measure
	 FROM #TEMPTABLE WHERE MONTHCOUNT='0.00'

	--SELECT * FROM #TEMPQUES
	IF (@PivotColumns IS NULL) BEGIN
	SET   @SQLQuery = 
		N'SELECT BUDGET,PROGRAM,SOFID,Performance_Measure,ELIGIBILITY, APP_NO, NAME,ACTIVITY_PROGRAM,ADDOPERATOR,CRITSEQ, FUND1,FUND2,FUND3,QType,CQDESC,CQRESP
		FROM  #TEMPQUES' 
	END
	ELSE BEGIN

	SET   @SQLQuery = 
		N'SELECT BUDGET,PROGRAM,SOFID,Performance_Measure,ELIGIBILITY, APP_NO, NAME,ACTIVITY_PROGRAM,ADDOPERATOR,CRITSEQ, FUND1,FUND2,FUND3,QType,CQDESC,CQRESP,' +   @PivotColumns + '
		FROM  #TEMPQUES
		PIVOT( MAX(QUESRESULT) 
		FOR  QUESTION IN (' + @PivotColumns + '))  AS P ' 
	END
				--SELECT   @SQLQuery
				--Execute dynamic query
	EXECUTE sp_executesql @SQLQuery


	SELECT * FROM @QuestionTable

	--select * from @ResultTable

	--  DROP TABLE #TEMPTABLE, #TEMPCASEACT
